### ISSUE TITLE
Duplicated output dir specified

### ISSUE THREAD

**Issue by freizl** [ghosert/grunt-applymin#1]
There are two places need to specify output dir
1. `endmin` option in `Gruntfile`
2. comment `beginmin: /to/path/xyz.js`

I think the second place is not necessary.

**Comment by ghosert** [comment]
To not to confuse the user, keep the duplication for now.

**Comment by ghosert** [comment]
Otherwise, if anyone could devise a better solution to resolve this duplication.

**Comment by ghosert** [comment]
Close this bug for now, since there is no better solution.
