### ISSUE TITLE
Suggestion - provide option to not check for target in template

### ISSUE THREAD

**Issue by cyberwombat** [ghosert/grunt-applymin#3]
When I used the plugin I got this message: 

```
 Warning: In the file: views/frontend.swig, the target filename: public/dist/public.min.js is not referred by any css/js tags. Use --force to continue.
```

The problem is that I don't want the concatenated file in my template as it is named - I upload my assets to Amazon buckets so the path is different.  Would be nice to have a flag that one can set to prevent that check from happening. I can get around it with my template tags but that's just messy. 

Thanks

**Comment by ghosert** [comment]
Is that easy for you to make sure at least you have "public/dist/public.min.js" as the suffix in your Amazon url path ? And then that will work.

If you updated your js files and re-run grunt-applymin, the reference filename will be updated correspondingly as well.

The design is to avoid change the minified js every time manually if only you could follow some convention.

**Comment by cyberwombat** [comment]
I can't use "public/dist/public.min.js" on Amazon or local - it's a server path not a url - my url locally is "/dist/public.min.js". The grunt config wants a server path but the template needs a url - they are rarely the same.
